### ISSUE TITLE
Correción ortográfica

### ISSUE THREAD

**Issue by Jus7RooIt** [aspnet/AspNetCore.Docs.es-es#31]
Reemplazar URI por URL en el titulo "Incorporación de un controlador"

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 20264150-9ac7-2b21-3314-64ffa114410f
* Version Independent ID: 3477519b-1bc2-73be-33e3-63067383d426
* Content: [Agregar un controlador a una aplicación de ASP.NET Core MVC](https://docs.microsoft.com/es-es/aspnet/core/tutorials/first-mvc-app/adding-controller?view=aspnetcore-2.2&tabs=visual-studio#feedback)
* Content Source: [aspnetcore/tutorials/first-mvc-app/adding-controller.md](https://github.com/aspnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/tutorials/first-mvc-app/adding-controller.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by Rick-Anderson** [comment]
URI is fine. Recommend closing issue.

**Comment by CeciAc** [comment]
Hola, @Jus7RooIt 


Gracias por sus comentarios lingüísticos.  

El autor del documento confirmó que "URI" es el término correcto.

Apreciamos su colaboración y le animamos a seguir enviándonos comentarios.  

Atentamente, 

Equipo internacional de Microsoft Docs
