### ISSUE TITLE
[Blazor] Translate multiple pages

### ISSUE THREAD

**Issue by mpetrinidev** [aspnet/AspNetCore.Docs.es-es#34]
I'd like to collaborate with the translation of Blazor's documentation.
How can I get involved in this? Or is it not possible?

Thank you!

**Comment by srvbpigh** [comment]
Hello, @mpetrinidev
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
@JasonCard can you please check this issue?

**Comment by JasonCard** [comment]
Hi @mpetrinidev, 

Thank you for raising this issue that Blazor documentation was not localized. 
It is currently not possible to collaborate with the translation of our documentation.
However, I will have this Blazor documentation localized immediately via machine translation, then consider human translation in the near future.

Kind regards,
Microsoft DOCS International Team
cc @CeciAc
