### ISSUE TITLE
Incorporación de los métodos CREATE y PUT

### ISSUE THREAD

**Issue by vpj-mati** [aspnet/AspNetCore.Docs.es-es#36]
En el ejemplo de la página nos muestra que para crear un método CREATE necesitamos el siguiente método
[HttpPost]
public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; PostTodoItem(TodoItem item)

Pero en mi caso al tratar de ejecutar el parámetro item siempre llegaba en con datos nulos. El problema se resuelve agregando el atributo [FromBody] como copio a continuación
[HttpPost]
public async Task&lt;ActionResult&lt;TodoItem&gt;&gt; PostTodoItem([FromBody]TodoItem item)

Lo mismo sucedía con el ejemplo del método PUT
[HttpPut("{id}")]
public async Task&lt;IActionResult&gt; PutTodoItem(long id, [FromBody]TodoItem item)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ Vinculación de problema de GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Creación de una API web con ASP.NET Core](https://docs.microsoft.com/es-es/aspnet/core/tutorials/first-web-api?view=aspnetcore-2.2&tabs=visual-studio#add-a-create-method)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @vpj-mati
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hola, @vpj-mati

Agradecemos enormemente su colaboración. Los comentarios están relacionados con la documentación original. 
Por lo tanto, migraremos este problema al repositorio de inglés. Revise el estado del problema aquí:  https://github.com/aspnet/AspNetCore.Docs/issues/13700
Apreciamos su contribución a nuestros artículos.  

Atentamente, 
Equipo internacional de Microsoft Docs
