### ISSUE TITLE
Why HelloWorldController in a Video Store Project?

### ISSUE THREAD

**Issue by kikoarquer** [aspnet/AspNetCore.Docs.es-es#38]
Hi. I found strange to start a Video Store Project (MvcMovie) and the tutorial uses as example a "HelloWorldController".   This breaks the linearity between the first class and the remaining ones. So, it's confuse to me: should I create the Controller with this name and erase it later, or it will be a permanent name in this project?...     My BR

**Comment by srvbpigh** [comment]
Hello, @kikoarquer
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @kikoarquer 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
