### ISSUE TITLE
StartupJquery changed to StartupJavaScript

### ISSUE THREAD

**Issue by juandelacruz23** [aspnet/AspNetCore.Docs.es-es#41]
There was a change in the sample code attached to this tutorial (3.0 version), where the file/class StartupJquery.cs was renamed to StartupJavaScript.cs, but [it's reference](https://github.com/aspnet/AspNetCore.Docs/blob/f4af5913336a809798f0652e9af4633d488b558c/aspnetcore/tutorials/first-web-api/samples/3.0/TodoApi/Program.cs#L24) in Program.cs wasn't updated; so it doesn't run 😢

This was referenced in https://github.com/aspnet/AspNetCore.Docs/issues/14771 (I was told to do a cross link but I don't know exactly what that is 🙃)

---
#### Detalles del documento

⚠ *No edite esta sección. Se requiere para docs.microsoft.com ➟ vinculación de problemas de GitHub.*

* ID: 583ae3e7-5915-f22b-e54c-6c100cf2a7da
* Version Independent ID: 95f2549e-29f9-e31a-b4d0-432b971643ff
* Content: [Tutorial: Creación de una API web con ASP.NET Core](https://docs.microsoft.com/es-mx/aspnet/core/tutorials/first-web-api?view=aspnetcore-3.0&tabs=visual-studio)
* Content Source: [aspnetcore/tutorials/first-web-api.md](https://github.com/aspnet/AspNetCore.Docs.es-es/blob/live/aspnetcore/tutorials/first-web-api.md)
* Product: **aspnet-core**
* Technology: **aspnetcore-tutorials**
* GitHub Login: @Rick-Anderson
* Microsoft Alias: **riande**

**Comment by srvbpigh** [comment]
Hello, @juandelacruz23
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by guardrex** [comment]
@juandelacruz23 When you paste in the link, GitHub cross-links the issues. There will be a link back over here from the issue that you linked here.

**Comment by lichasu** [comment]
Hi @juandelacruz23 

This issue was already solved in https://github.com/aspnet/AspNetCore.Docs/pull/14775.

These changes will automatically show up in all localized files in the next localization round.

Thanks for your contribution!
